In [1]:
import pandas as pd
import re

In [2]:
from metrics import confusion_matrix, metrics

In [3]:
df = pd.read_csv('data/simple_data.csv')

In [4]:
matrix = confusion_matrix(df.masked, df.masked)

In [5]:
matrix

          entity  TP  FP  FN
0      [ADDRESS]   2   0   0
1  [CARD_NUMBER]   2   0   0
2        [EMAIL]   4   0   0
3         [NAME]   7   0   0
4     [PASSPORT]   3   0   0
5        [PHONE]   3   0   0
6      __TOTAL__  21   0   0

In [6]:
metrics(df.masked, df.masked)

          entity  Precision  Recall   F1
0      [ADDRESS]        1.0     1.0  1.0
1  [CARD_NUMBER]        1.0     1.0  1.0
2        [EMAIL]        1.0     1.0  1.0
3         [NAME]        1.0     1.0  1.0
4     [PASSPORT]        1.0     1.0  1.0
5        [PHONE]        1.0     1.0  1.0
6      __TOTAL__        1.0     1.0  1.0

In [8]:
df_res = pd.read_csv('data/analysis_results.csv')

In [10]:
df_res

,id,text,target,pred,is_match,mapping
0,2,Здравствуйте меня зовут Иван Иванов хочу узнат...,Здравствуйте меня зовут [NAME] хочу узнать поч...,Здравствуйте меня зовут [NAME] хочу узнать поч...,1,{'[NAME_1]': 'Иван Иванов'}
1,3,Добрый день это Петр Петров я не могу войти в ...,Добрый день это [NAME] я не могу войти в мобил...,Добрый день это [NAME] я не могу войти в мобил...,1,{'[NAME_1]': 'Петр Петров'}
2,4,Меня зовут Сергей Сидоров у меня возникла проб...,Меня зовут [NAME] у меня возникла проблема с п...,Меня зовут [NAME] у меня возникла проблема с п...,1,{'[NAME_1]': 'Сергей Сидоров'}
3,5,Здравствуйте меня зовут Анна Кузнецова я хочу ...,Здравствуйте меня зовут [NAME] я хочу изменить...,Здравствуйте меня зовут [NAME] я хочу изменить...,1,{'[NAME_1]': 'Анна Кузнецова'}
4,6,Я клиент банка Иван Иванов и у меня не проходи...,Я клиент банка [NAME] и у меня не проходит пла...,Я клиент банка [NAME] и у меня не проходит пла...,1,{'[NAME_1]': 'Иван Иванов'}
...,...,...,...,...,...,...
61,63,Помогите разобраться с доступом использовал да...,Помогите разобраться с доступом использовал да...,Помогите разобраться с доступом использовал да...,1,{'[CARD_1]': '5536 9100 1122 3344'}
62,64,При попытке входа система просит подтвердить д...,При попытке входа система просит подтвердить д...,При попытке входа система просит подтвердить д...,1,{'[PHONE_1]': '89167778899'}
63,65,Не получается восстановить доступ указывал так...,Не получается восстановить доступ указывал так...,Не получается восстановить доступ указывал так...,1,{'[EMAIL_1]': 'helpclient@mail.ru'}
64,66,Пытаюсь войти в систему данные которые вводил ...,Пытаюсь войти в систему данные которые вводил ...,Пытаюсь войти в систему данные которые вводил ...,1,"{'[NAME_1]': 'Иван Иванов', '[PHONE_1]': '8916..."
65,67,Не получается выполнить вход пробовал использо...,Не получается выполнить вход пробовал использо...,Не получается выполнить вход пробовал использо...,1,{'[CARD_1]': '4276 9999 8888 7777'}

In [11]:
metrics(df_res.target, df_res.pred)

       entity  Precision    Recall        F1
0   [ADDRESS]        1.0  0.750000  0.857143
1      [CARD]        1.0  1.000000  1.000000
2     [EMAIL]        1.0  1.000000  1.000000
3      [NAME]        1.0  0.829268  0.906667
4  [PASSPORT]        1.0  1.000000  1.000000
5     [PHONE]        1.0  1.000000  1.000000
6   __TOTAL__        1.0  0.915888  0.956098