# Тестирование модели на простом датасете из 100 строк

In [31]:
import pandas as pd
import re
from masker import mask_pii

In [32]:
from metrics import confusion_matrix, metrics

In [33]:
df_simple_100= pd.read_csv('data/simple_data_100.csv')

In [34]:
df_simple_100['pred'] = df_simple_100.original.apply(lambda x: mask_pii(x))

In [35]:
df_simple_100.sample(10)

,original,masked,pred
67,Измените лимит на снятие наличных по карте 427...,Измените лимит на снятие наличных по карте [CARD],Измените лимит на снятие наличных по карте [CARD]
89,"Добрый день, я хочу подключить уведомления о б...","Добрый день, я хочу подключить уведомления о б...","Добрый день, я хочу подключить уведомления о б..."
8,"Здравствуйте, как закрыть кредит досрочно? Я К...","Здравствуйте, как закрыть кредит досрочно? Я [...","Здравствуйте, как закрыть кредит досрочно? Я [..."
80,"Мой email: maksim.volkov@mail.ru, пришлите гра...","Мой email: [EMAIL], пришлите график платежей","Мой email: [EMAIL], пришлите график платежей"
47,"Измените адрес доставки карты на: Москва, улиц...",Измените адрес доставки карты на: [ADDRESS],"Измените адрес доставки карты на: [ADDRESS], у..."
33,"Добрый день, у меня списались деньги дважды за...","Добрый день, у меня списались деньги дважды за...","Добрый день, у меня списались деньги дважды за..."
82,"Подскажите, можно ли оплатить кредит картой др...","Подскажите, можно ли оплатить кредит картой др...","Подскажите, можно ли оплатить кредит картой др..."
14,"Я Сидоров Петр Иванович, паспорт 4507123456, х...","Я [NAME], паспорт [PASSPORT], хочу уточнить гр...","Я [NAME], паспорт [PASSPORT], хочу уточнить гр..."
63,"Здравствуйте, мой email: kozlov@inbox.ru, не п...","Здравствуйте, мой email: [EMAIL], не получаю p...","Здравствуйте, мой email: [EMAIL], не получаю p..."
30,"Здравствуйте, мой email s.ivanov@inbox.ru, при...","Здравствуйте, мой email [EMAIL], пришлите дого...","Здравствуйте, мой email [EMAIL], пришлите дого..."

In [36]:
metrics(df_simple_100.masked, df_simple_100.pred)

       entity  Precision    Recall        F1
0   [ADDRESS]   0.650000  1.000000  0.787879
1      [CARD]   1.000000  1.000000  1.000000
2     [EMAIL]   1.000000  1.000000  1.000000
3      [NAME]   1.000000  0.954545  0.976744
4  [PASSPORT]   1.000000  1.000000  1.000000
5     [PHONE]   1.000000  1.000000  1.000000
6   __TOTAL__   0.935185  0.990196  0.961905

Есть проблема с определением адреса, адрес определяется не всегда полностью, но определяются все адреса. Определяются не все имена и не полностью.

In [37]:
# Строки, в которых модель ошиблась
df_simple_100[df_simple_100.masked!=df_simple_100.pred]

,original,masked,pred
10,"Я прописана по адресу: Екатеринбург, ул. Ленин...","Я прописана по адресу: [ADDRESS], нужно сменит...","Я прописана по адресу: [ADDRESS], ул. Ленина, ..."
19,"Я Морозова Елена, проживаю в Самаре, улица Мос...","Я [NAME], проживаю в [ADDRESS], потеряла паспорт","Я [NAME], проживаю в [ADDRESS], улица [ADDRESS..."
21,"Мой номер для связи +79851112233, перезвоните мне","Мой номер для связи [PHONE], перезвоните мне","Мой номер для связи +[PHONE], перезвоните мне"
24,"Моя новая прописка: Казань, проспект Победы, д...",Моя новая прописка: [ADDRESS],"Моя новая прописка: [ADDRESS], проспект Победы..."
32,"Я живу в Новосибирске, на улице Советской, д. ...","Я живу в [ADDRESS], как мне получить карту кур...","Я живу в [ADDRESS], на улице [ADDRESS], д. 20,..."
40,"Мой адрес регистрации изменился, теперь я в Ро...","Мой адрес регистрации изменился, теперь я в [A...","Мой адрес регистрации изменился, теперь я в [A..."
47,"Измените адрес доставки карты на: Москва, улиц...",Измените адрес доставки карты на: [ADDRESS],"Измените адрес доставки карты на: [ADDRESS], у..."
57,"Я Морозов Игорь, проживаю в Красноярске, ул. М...","Я [NAME], проживаю в [ADDRESS], хочу открыть в...","Я [NAME], проживаю в [ADDRESS], ул. Мира, д. 3..."
62,"Мой адрес: Воронеж, ул. Плехановская, д. 10, к...","Мой адрес: [ADDRESS], пришлите письмом","Мой адрес: [ADDRESS], ул. Плехановская, д. 10,..."
70,"Подскажите, есть ли отделение рядом с метро Пл...","Подскажите, есть ли отделение рядом с метро Пл...","Подскажите, есть ли отделение рядом с метро [A..."
71,"Я Крылова Анна Ивановна, проживаю в Нижнем Нов...","Я [NAME], проживаю в [ADDRESS]","Я Крылова Анна Ивановна, проживаю в [ADDRESS],..."
72,"Мой номер 79049998877, смените тариф на Премиум","Мой номер [PHONE], смените тариф на Премиум","Мой номер [PHONE], смените тариф на [ADDRESS]"
77,Измените адрес прописки в системе: теперь Санк...,Измените адрес прописки в системе: теперь [ADD...,Измените адрес прописки в системе: теперь [ADD...
86,"Здравствуйте, мой адрес: Уфа, ул. Октября, д. ...","Здравствуйте, мой адрес: [ADDRESS], хочу заказ...","Здравствуйте, мой адрес: [ADDRESS], ул. Октябр..."
93,"Измените адрес для корреспонденции: Пермь, ул....",Измените адрес для корреспонденции: [ADDRESS],"Измените адрес для корреспонденции: [ADDRESS],..."
102,"Я Жуков Антон, проживаю в Тюмени, ул. Республи...","Я [NAME], проживаю в [ADDRESS], жду карту","Я [NAME], проживаю в [ADDRESS], ул. Республики..."