In [1]:
import pandas as pd
import numpy as np
from metics import metrics

In [2]:
df_train = pd.read_csv('data/train_dataset.tsv', sep='\t')

In [3]:
df_train.sample(10)

,text,target,entity
8232,Мы не предоставляем детализацию звонков. Могу ...,[],empty
5237,Запросил код 221098 для подтверждения операции...,"[(13, 19, 'Одноразовые коды')]",['221098']
144,"Подскажите, пожалуйста, как правильно использо...","[(61, 79, 'API ключи')]",['secret_key_app_456']
7054,"Да, вижу поступление. Отправитель известен, но...","[(76, 88, 'Сведения об ИНН')]",['502300000008']
2714,Изменение данных о регистрации требует верифик...,[],empty
4243,Мне нужно срочно заблокировать счет 4081781075...,"[(36, 56, 'Номер банковского счета')]",['40817810755566677788']
1613,Мне нужна справка для получения визы в Великоб...,"[(39, 53, 'Гражданство и названия стран'), (93...","['Великобританию', 'Великобритании']"
3393,"Мне нужно подтвердить операцию по телефону, но...","[(69, 75, 'Кодовые слова')]",['Победа']
2545,Моя временная регистрация до 04.04.2025. Могу ...,"[(29, 39, 'Дата регистрации по месту жительств...",['04.04.2025']
6369,"Почтовое отправление вернулось. Проверьте, пож...","[(77, 91, 'Полный адрес'), (120, 125, 'Полный ...","['Самарская обл.', 'д. 99', 'кв. 25', 'Россия'..."

In [4]:
metrics(df_train['target'], df_train['target'])

,entity,TP,FP,FN,Precision,Recall,F1
0,API ключи,337,0,0,1.0,1.0,1.0
1,CVV/CVC,208,0,0,1.0,1.0,1.0
2,Email,129,0,0,1.0,1.0,1.0
3,Водительское удостоверение,278,0,0,1.0,1.0,1.0
4,Временное удостоверение личности,165,0,0,1.0,1.0,1.0
5,Гражданство и названия стран,333,0,0,1.0,1.0,1.0
6,Данные об автомобиле клиента,302,0,0,1.0,1.0,1.0
7,"Данные об организации/юридическом лице (ИНН, К...",296,0,0,1.0,1.0,1.0
8,Дата окончания срока действия карты,238,0,0,1.0,1.0,1.0
9,Дата регистрации по месту жительства или пребы...,192,0,0,1.0,1.0,1.0
10,Дата рождения,362,0,0,1.0,1.0,1.0
11,Имя держателя карты,171,0,0,1.0,1.0,1.0
12,Кодовые слова,143,0,0,1.0,1.0,1.0
13,Место рождения,324,0,0,1.0,1.0,1.0
14,Наименование банка,163,0,0,1.0,1.0,1.0
15,Номер банковского счета,225,0,0,1.0,1.0,1.0
16,Номер карты,141,0,0,1.0,1.0,1.0
17,Номер телефона,280,0,0,1.0,1.0,1.0
18,Одноразовые коды,139,0,0,1.0,1.0,1.0
19,ПИН код,141,0,0,1.0,1.0,1.0
20,Пароли,146,0,0,1.0,1.0,1.0
21,Паспортные данные,256,0,0,1.0,1.0,1.0
22,Полный адрес,811,0,0,1.0,1.0,1.0
23,Разрешение на работу / визу,307,0,0,1.0,1.0,1.0
24,СНИЛС клиента,133,0,0,1.0,1.0,1.0
25,Сведения об ИНН,270,0,0,1.0,1.0,1.0
26,Свидетельство о рождении,138,0,0,1.0,1.0,1.0
27,Серия и номер вида на жительство,104,0,0,1.0,1.0,1.0
28,Содержимое магнитной полосы,172,0,0,1.0,1.0,1.0
29,ФИО,254,0,0,1.0,1.0,1.0
30,__TOTAL__,7158,0,0,1.0,1.0,1.0

In [5]:
metrics(df_train['target'], df_train['target'])['entity'].unique()

<StringArray>
[                                                                           'API ключи',
                                                                              'CVV/CVC',
                                                                                'Email',
                                                           'Водительское удостоверение',
                                                     'Временное удостоверение личности',
                                                         'Гражданство и названия стран',
                                                         'Данные об автомобиле клиента',
 'Данные об организации/юридическом лице (ИНН, КПП, ОГРН, БИК, адреса, расчётный счёт)',
                                                  'Дата окончания срока действия карты',
                                  'Дата регистрации по месту жительства или пребывания',
                                                                        'Дата рождения',
                                                                  'Имя держателя карты',
                                                                        'Кодовые слова',
                                                                       'Место рождения',
                                                                   'Наименование банка',
                                                              'Номер банковского счета',
                                                                          'Номер карты',
                                                                       'Номер телефона',
                                                                     'Одноразовые коды',
                                                                              'ПИН код',
                                                                               'Пароли',
                                                                    'Паспортные данные',
                                                                         'Полный адрес',
                                                          'Разрешение на работу / визу',
                                                                        'СНИЛС клиента',
                                                                      'Сведения об ИНН',
                                                             'Свидетельство о рождении',
                                                     'Серия и номер вида на жительство',
                                                          'Содержимое магнитной полосы',
                                                                                  'ФИО',
                                                                            '__TOTAL__']
Length: 31, dtype: str